# Generated by Django 3.0.7 on 2020-06-12 07:36

from django.db import migrations, models
import django.db.models.deletion
import meetings.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True, max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(blank=True, max_length=200)),
                ('contact_number', models.CharField(blank=True, max_length=50, verbose_name='Contact Number')),
                ('department', models.ForeignKey(default=meetings.models.get_dgh_id, on_delete=django.db.models.deletion.SET_DEFAULT, to='meetings.Department')),
            ],
        ),
        migrations.CreateModel(
            name='Meetings',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('subject', models.TextField(max_length=100, verbose_name='Purpose/Subject')),
                ('company', models.CharField(max_length=500)),
                ('name', models.CharField(max_length=100, verbose_name='Full Name')),
                ('email', models.EmailField(max_length=100, verbose_name='Official EMail')),
                ('contact_no', models.CharField(max_length=10, verbose_name='Contact Number')),
                ('date_time', models.DateTimeField(verbose_name='Proposed Date & Time')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('requested_official', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='meetings.Employee', verbose_name='Official')),
            ],
        ),
    ]
