# Generated by Django 3.0.7 on 2020-06-26 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0003_updated_fields2'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormOTPCaptchaPairs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('captcha', models.CharField(max_length=100, verbose_name='Captcha String')),
                ('otp', models.IntegerField(verbose_name='Generated OTP')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('valid_till', models.DateTimeField(verbose_name='Valid Until')),
            ],
        ),
        migrations.AddField(
            model_name='employee',
            name='order_number',
            field=models.IntegerField(default=1, unique=True, verbose_name='Site Order'),
            preserve_default=False,
        ),
    ]
