# Generated by Django 3.0.7 on 2020-07-06 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0005_MadeFieldsOptional'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetings',
            name='date_time2',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Proposed Date & Time - Option 2'),
        ),
        migrations.AlterField(
            model_name='meetings',
            name='date_time3',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Proposed Date & Time - Option 3'),
        ),
        migrations.AlterField(
            model_name='meetings',
            name='duration2',
            field=models.IntegerField(blank=True, null=True, verbose_name='Proposed Duration(minutes) - Option 2'),
        ),
        migrations.AlterField(
            model_name='meetings',
            name='duration3',
            field=models.IntegerField(blank=True, null=True, verbose_name='Proposed Duration(minutes) - Option 3'),
        ),
    ]
