# Generated by Django 3.0.7 on 2020-07-07 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0006_MadeFieldsNullable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formotpcaptchapairs',
            name='captcha',
        ),
        migrations.AddField(
            model_name='formotpcaptchapairs',
            name='company',
            field=models.CharField(default='DGH', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='formotpcaptchapairs',
            name='contact_no',
            field=models.CharField(default='111111', max_length=10, verbose_name='Contact Number'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='formotpcaptchapairs',
            name='designation',
            field=models.CharField(default='Test', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='formotpcaptchapairs',
            name='email',
            field=models.EmailField(default='test@gmail.com', max_length=100, verbose_name='Official EMail'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='formotpcaptchapairs',
            name='name',
            field=models.CharField(default='NoName', max_length=100, verbose_name='Full Name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='meetings',
            name='status',
            field=models.IntegerField(choices=[(1, 'SUBMITTED'), (2, 'PENDING APPROVAL'), (3, 'APPROVED'), (4, 'REJECTED'), (5, 'EXPIRED')], default=1, verbose_name='Status'),
            preserve_default=False,
        ),
    ]
