# Generated by Django 3.0.7 on 2020-07-07 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0007_UpdatedMeetingStatus_OTPTables'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FormOTPCaptchaPairs',
            new_name='FormOTP',
        ),
    ]
